classDiagram

    class Dataset {
        <<Abstract>>
        +Dict metadata
        +__init__(metadata: Dict[str, Any])
    }

    class Input {
        -InputSource _source
        +read(spark, filter_params)
    }

    class Output {
        +df(spark: SparkSession) DataFrame
        +writer(df: DataFrame) Union[DataFrameWriter, DataFrameWriterV2, DataStreamWriter]
        +write(df: DataFrame) None
    }

    class InputConfig {
        +str source_type
        +str path
        +Optional[str] format
        +Optional[Dict] options
    }

    class FilterStrategy {
        <<abstract>>
        +apply_filter(source_path, filter_params)*
    }

    class FileListFilterStrategy {
        +apply_filter(source_path, filter_params)
    }

    class SqlFilterStrategy {
        +apply_filter(source_path, filter_params)
    }

    class InputSourceFactory {
        +create_input_source(config) InputSource
    }

    class InputSource {
        <<abstract>>
        -FilterStrategy _filter_strategy
        -InputConfig config
        +read(spark, filter_params)*
        #_create_filter_strategy()*
    }

    class FileInputSource {
        +read(spark, filter_params)
        #_create_filter_strategy()
    }

    class TableInputSource {
        +read(spark, filter_params)
        #_create_filter_strategy()
    }

    Dataset <|-- Input
    Dataset <|-- Output
    FilterStrategy <|-- FileListFilterStrategy
    FilterStrategy <|-- SqlFilterStrategy
    InputSource <|-- FileInputSource
    InputSource <|-- TableInputSource
    InputSource o-- FilterStrategy
    Input o-- InputSource
    InputSourceFactory ..> InputSource
    InputSource o-- InputConfig
