name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9.19, 3.10.14, 3.11.9]
        spark-version: [3.3.4, 3.4.3, 3.5.1]
        include:
          - spark-version: 3.3.4
            delta-version: 2.3.0
          - spark-version: 3.4.3
            delta-version: 2.4.0
          - spark-version: 3.5.1
            delta-version: 3.2.0

    steps:
    - uses: actions/checkout@v3

    - name: Run tests
      run: |
        docker pull zetaco/dtb:py${{ matrix.python-version }}-spark${{ matrix.spark-version }}-delta${{ matrix.delta-version }}
        docker run --rm -v $(pwd):/app zetaco/dtb:py${{ matrix.python-version }}-spark${{ matrix.spark-version }}-delta${{ matrix.delta-version }} bash -c 'pip install --no-deps -e . && pytest -vv'

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [test]
    environment: release
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install build setuptools wheel twine
    - name: Build
      run: |
        python -m build
    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
